# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ubuntu-24.04	
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v4

      - name: System deps
        run: sudo apt-get install libcurl4-openssl-dev libxslt1-dev libharfbuzz-dev libfribidi-dev libfontconfig1-dev pandoc texlive

      - uses: r-lib/actions/setup-r@v2

      - name: Set the repositories
        run: |
          echo 'options(repos = c(
            carpentries = "https://carpentries.r-universe.dev/", 
            CRAN = "https://packagemanager.posit.co/cran/__linux__/noble/latest"
          ))' >> ~/.Rprofile

      - name: Install package
        run: |
          install.packages("remotes")
          remotes::install_local(dependencies = TRUE)
        shell: Rscript {0}
    
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
